/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/players/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPlayer"];
        put: operations["updatePlayer"];
        post?: never;
        delete: operations["deletePlayer"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clubs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getClub"];
        put: operations["updateClub"];
        post?: never;
        delete: operations["deleteClub"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllMatches"];
        put?: never;
        post: operations["registerMatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/{matchId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMatchEvents"];
        put?: never;
        post: operations["recordEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllPlayers"];
        put?: never;
        post: operations["createPlayer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clubs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllClubs"];
        put?: never;
        post: operations["createClub"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/{matchId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMatch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/{matchId}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMatchState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PlayerDTO: {
            /** Format: uuid */
            id?: string;
            name: string;
            /** Format: uuid */
            club: string;
        };
        /** @description A rejected property of the request payload. */
        ApiFieldError: {
            /**
             * @description Identifier of the violated constraint.
             * @example REQUIRED_NOT_BLANK
             */
            code?: string;
            /**
             * @description Name of the rejected property.
             * @example name
             */
            property?: string;
            /**
             * @description Explanation of the violated constraint.
             * @example must not be blank
             */
            message?: string;
            /** @description Value that was rejected. */
            rejectedValue?: unknown;
            /**
             * @description Full path of the property inside the payload. Differs from "property" only for a nested object.
             * @example name
             */
            path?: string;
        };
        /** @description Body returned when the request payload fails validation. The code is always VALIDATION_FAILED. */
        ApiValidationError: {
            /**
             * Format: int32
             * @description HTTP status code, repeated in the body for clients that cannot read it from the response line.
             * @example 404
             */
            status?: number;
            /**
             * @description Stable machine-readable identifier of the failure.
             * @example MATCH_NOT_FOUND
             */
            code: string;
            /**
             * @description Human-readable explanation, safe to show to a client.
             * @example Match 3f2b1c9e-0a4d-4a7e-8b12-8d5f6c7e9a01 does not exist
             */
            message: string;
            /**
             * Format: date-time
             * @description Moment the error was produced, used to match a client report against the server log line. Added by an ApiErrorResponseCustomizer, so it is present on every error the exception handler produces.
             * @example 2026-09-03T14:35:12.482+02:00
             */
            timestamp?: string;
            /** @description One entry per rejected property of the request payload. */
            fieldErrors?: components["schemas"]["ApiFieldError"][];
        };
        /** @description Body returned when a request value cannot be converted to the expected type. The code is always ARGUMENT_TYPE_MISMATCH. */
        ApiTypeMismatchError: {
            /**
             * Format: int32
             * @description HTTP status code, repeated in the body for clients that cannot read it from the response line.
             * @example 404
             */
            status?: number;
            /**
             * @description Stable machine-readable identifier of the failure.
             * @example MATCH_NOT_FOUND
             */
            code: string;
            /**
             * @description Human-readable explanation, safe to show to a client.
             * @example Match 3f2b1c9e-0a4d-4a7e-8b12-8d5f6c7e9a01 does not exist
             */
            message: string;
            /**
             * Format: date-time
             * @description Moment the error was produced, used to match a client report against the server log line. Added by an ApiErrorResponseCustomizer, so it is present on every error the exception handler produces.
             * @example 2026-09-03T14:35:12.482+02:00
             */
            timestamp?: string;
            /**
             * @description Type the handler expects for the value.
             * @example java.util.UUID
             */
            expectedType?: string;
            /**
             * @description Name of the parameter that carried the value.
             * @example matchId
             */
            property?: string;
            /**
             * @description Value that could not be converted.
             * @example not-a-uuid
             */
            rejectedValue?: unknown;
        };
        /** @description Body returned for every failed request. */
        ApiError: {
            /**
             * Format: int32
             * @description HTTP status code, repeated in the body for clients that cannot read it from the response line.
             * @example 404
             */
            status?: number;
            /**
             * @description Stable machine-readable identifier of the failure.
             * @example MATCH_NOT_FOUND
             */
            code: string;
            /**
             * @description Human-readable explanation, safe to show to a client.
             * @example Match 3f2b1c9e-0a4d-4a7e-8b12-8d5f6c7e9a01 does not exist
             */
            message: string;
            /**
             * Format: date-time
             * @description Moment the error was produced, used to match a client report against the server log line. Added by an ApiErrorResponseCustomizer, so it is present on every error the exception handler produces.
             * @example 2026-09-03T14:35:12.482+02:00
             */
            timestamp?: string;
        };
        IdResponseDTO: {
            /** Format: uuid */
            id?: string;
        };
        ClubDTO: {
            /** Format: uuid */
            id?: string;
            name: string;
            country: string;
        };
        CreateMatchRequest: {
            /** Format: date-time */
            scheduledKickoff: string;
            venue: string;
            /** Format: uuid */
            homeTeamId: string;
            /** Format: uuid */
            awayTeamId: string;
        };
        CreateMatchResponse: {
            /** Format: uuid */
            matchId?: string;
        };
        AbandonMatch: {
            type: "AbandonMatch";
        } & (Omit<components["schemas"]["MatchCommand"], "type"> & {
            reason?: string;
            /** Format: int32 */
            minute?: number;
        });
        AnnounceAddedTime: {
            type: "AnnounceAddedTime";
        } & (Omit<components["schemas"]["MatchCommand"], "type"> & {
            /** Format: int32 */
            addedMinutes: number;
        });
        AwardPenalty: {
            type: "AwardPenalty";
        } & (Omit<components["schemas"]["MatchCommand"], "type"> & {
            /** Format: uuid */
            clubId: string;
            /** Format: int32 */
            minute: number;
        });
        BlowFullTime: {
            type: "BlowFullTime";
        } & Omit<components["schemas"]["MatchCommand"], "type">;
        CancelGoal: {
            type: "CancelGoal";
        } & (Omit<components["schemas"]["MatchCommand"], "type"> & {
            /** Format: uuid */
            clubId: string;
            /** Format: int32 */
            minute: number;
        });
        EndFirstHalf: {
            type: "EndFirstHalf";
        } & Omit<components["schemas"]["MatchCommand"], "type">;
        GiveRedCard: {
            type: "GiveRedCard";
        } & (Omit<components["schemas"]["MatchCommand"], "type"> & {
            /** Format: uuid */
            clubId: string;
            /** Format: uuid */
            playerId: string;
            /** Format: int32 */
            minute: number;
        });
        GiveYellowCard: {
            type: "GiveYellowCard";
        } & (Omit<components["schemas"]["MatchCommand"], "type"> & {
            /** Format: uuid */
            clubId: string;
            /** Format: uuid */
            playerId: string;
            /** Format: int32 */
            minute: number;
        });
        MatchCommand: {
            type: string;
        };
        MissPenalty: {
            type: "MissPenalty";
        } & (Omit<components["schemas"]["MatchCommand"], "type"> & {
            /** Format: uuid */
            clubId: string;
            /** Format: uuid */
            playerId: string;
            /** Format: int32 */
            minute: number;
        });
        PostponeMatch: {
            type: "PostponeMatch";
        } & (Omit<components["schemas"]["MatchCommand"], "type"> & {
            reason?: string;
        });
        RecordVarDecision: {
            type: "RecordVarDecision";
        } & (Omit<components["schemas"]["MatchCommand"], "type"> & {
            decision: string;
            /** Format: int32 */
            minute: number;
        });
        ScoreGoal: {
            type: "ScoreGoal";
        } & (Omit<components["schemas"]["MatchCommand"], "type"> & {
            /** Format: uuid */
            clubId: string;
            /** Format: uuid */
            playerId: string;
            /** Format: int32 */
            minute: number;
        });
        ScoreOwnGoal: {
            type: "ScoreOwnGoal";
        } & (Omit<components["schemas"]["MatchCommand"], "type"> & {
            /** Format: uuid */
            clubId: string;
            /** Format: uuid */
            playerId: string;
            /** Format: int32 */
            minute: number;
        });
        ScorePenalty: {
            type: "ScorePenalty";
        } & (Omit<components["schemas"]["MatchCommand"], "type"> & {
            /** Format: uuid */
            clubId: string;
            /** Format: uuid */
            playerId: string;
            /** Format: int32 */
            minute: number;
        });
        StartMatch: {
            type: "StartMatch";
        } & Omit<components["schemas"]["MatchCommand"], "type">;
        StartSecondHalf: {
            type: "StartSecondHalf";
        } & Omit<components["schemas"]["MatchCommand"], "type">;
        StartVarCheck: {
            type: "StartVarCheck";
        } & (Omit<components["schemas"]["MatchCommand"], "type"> & {
            reason: string;
            /** Format: int32 */
            minute: number;
        });
        Substitute: {
            type: "Substitute";
        } & (Omit<components["schemas"]["MatchCommand"], "type"> & {
            /** Format: uuid */
            clubId: string;
            /** Format: uuid */
            playerOutId: string;
            /** Format: uuid */
            playerInId: string;
            /** Format: int32 */
            minute: number;
        });
        MatchResponse: {
            /** Format: uuid */
            matchId?: string;
            /** Format: date-time */
            scheduledKickoff?: string;
            /** @enum {string} */
            status?: "SCHEDULED" | "IN_PROGRESS" | "HALF_TIME" | "COMPLETED" | "POSTPONED" | "ABANDONED";
            homeClubName?: string;
            awayClubName?: string;
        };
        MatchStateDTO: {
            /** Format: uuid */
            matchId?: string;
            /** @enum {string} */
            status?: "SCHEDULED" | "IN_PROGRESS" | "HALF_TIME" | "COMPLETED" | "POSTPONED" | "ABANDONED";
            homeClubName?: string;
            awayClubName?: string;
            /** Format: int32 */
            homeScore?: number;
            /** Format: int32 */
            awayScore?: number;
            /** Format: int32 */
            homeYellows?: number;
            /** Format: int32 */
            awayYellows?: number;
            /** Format: int32 */
            homeReds?: number;
            /** Format: int32 */
            awayReds?: number;
            /** Format: int32 */
            homeSubs?: number;
            /** Format: int32 */
            awaySubs?: number;
        };
        MatchEventDTO: {
            /** Format: int32 */
            sequenceNumber?: number;
            /** @enum {string} */
            type?: "MATCH_SCHEDULED" | "MATCH_STARTED" | "FIRST_HALF_ENDED" | "SECOND_HALF_STARTED" | "FULL_TIME" | "MATCH_ABANDONED" | "MATCH_POSTPONED" | "GOAL_SCORED" | "OWN_GOAL" | "GOAL_CANCELED" | "YELLOW_CARD_GIVEN" | "RED_CARD_GIVEN" | "SECOND_YELLOW_CARD" | "SUBSTITUTION" | "PENALTY_AWARDED" | "PENALTY_SCORED" | "PENALTY_MISSED" | "VAR_CHECK_STARTED" | "VAR_DECISION" | "ADDED_TIME_ANNOUNCED";
            /** Format: int32 */
            minute?: number;
            isHomeClub?: boolean;
            playerName?: string;
            playerInName?: string;
            playerOutName?: string;
            /** Format: int32 */
            addedMinutes?: number;
            reason?: string;
            decision?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getPlayer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerDTO"];
                };
            };
            /** @description An identifier in the path is not a valid UUID. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 400,
                     *       "code": "ARGUMENT_TYPE_MISMATCH",
                     *       "message": "Failed to convert value of type 'java.lang.String' to required type 'java.util.UUID'",
                     *       "timestamp": "2026-09-03T14:35:12.482+02:00",
                     *       "expectedType": "java.util.UUID",
                     *       "property": "matchId",
                     *       "rejectedValue": "not-a-uuid"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiTypeMismatchError"];
                };
            };
            /** @description No resource exists for the given identifier. The code names the resource: CLUB_NOT_FOUND, PLAYER_NOT_FOUND or MATCH_NOT_FOUND. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 404,
                     *       "code": "MATCH_NOT_FOUND",
                     *       "message": "Match 3f2b1c9e-0a4d-4a7e-8b12-8d5f6c7e9a01 does not exist",
                     *       "timestamp": "2026-09-03T14:35:12.482+02:00"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unexpected failure, or stored match data that is inconsistent (MATCH_STREAM_CORRUPTED, MATCH_PROJECTION_OUT_OF_SYNC). The incident is logged with the timestamp returned in the body. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 500,
                     *       "code": "MATCH_STREAM_CORRUPTED",
                     *       "message": "Stored match data is inconsistent. The incident has been logged.",
                     *       "timestamp": "2026-09-03T14:35:12.482+02:00"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    updatePlayer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlayerDTO"];
            };
        };
        responses: {
            /** @description Request succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdResponseDTO"];
                };
            };
            /** @description The payload fails validation (code VALIDATION_FAILED), carries a value that cannot be converted to its declared type (ARGUMENT_TYPE_MISMATCH), or references data that does not belong together (CLUB_NOT_IN_MATCH, PLAYER_NOT_IN_CLUB). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiValidationError"] | components["schemas"]["ApiTypeMismatchError"];
                };
            };
            /** @description No access token was sent, or the token is expired or invalid. Written by the security entry point, which emits only a code and a message. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "INSUFFICIENT_AUTHENTICATION",
                     *       "message": "Full authentication is required to access this resource"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The token is valid but the caller lacks the required role. Written by the security access denied handler, which emits only a code and a message. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "ACCESS_DENIED",
                     *       "message": "Access is denied"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No resource exists for the given identifier. The code names the resource: CLUB_NOT_FOUND, PLAYER_NOT_FOUND or MATCH_NOT_FOUND. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 404,
                     *       "code": "MATCH_NOT_FOUND",
                     *       "message": "Match 3f2b1c9e-0a4d-4a7e-8b12-8d5f6c7e9a01 does not exist",
                     *       "timestamp": "2026-09-03T14:35:12.482+02:00"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unexpected failure, or stored match data that is inconsistent (MATCH_STREAM_CORRUPTED, MATCH_PROJECTION_OUT_OF_SYNC). The incident is logged with the timestamp returned in the body. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 500,
                     *       "code": "MATCH_STREAM_CORRUPTED",
                     *       "message": "Stored match data is inconsistent. The incident has been logged.",
                     *       "timestamp": "2026-09-03T14:35:12.482+02:00"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    deletePlayer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resource deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description An identifier in the path is not a valid UUID. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 400,
                     *       "code": "ARGUMENT_TYPE_MISMATCH",
                     *       "message": "Failed to convert value of type 'java.lang.String' to required type 'java.util.UUID'",
                     *       "timestamp": "2026-09-03T14:35:12.482+02:00",
                     *       "expectedType": "java.util.UUID",
                     *       "property": "matchId",
                     *       "rejectedValue": "not-a-uuid"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiTypeMismatchError"];
                };
            };
            /** @description No access token was sent, or the token is expired or invalid. Written by the security entry point, which emits only a code and a message. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "INSUFFICIENT_AUTHENTICATION",
                     *       "message": "Full authentication is required to access this resource"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The token is valid but the caller lacks the required role. Written by the security access denied handler, which emits only a code and a message. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "ACCESS_DENIED",
                     *       "message": "Access is denied"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No resource exists for the given identifier. The code names the resource: CLUB_NOT_FOUND, PLAYER_NOT_FOUND or MATCH_NOT_FOUND. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 404,
                     *       "code": "MATCH_NOT_FOUND",
                     *       "message": "Match 3f2b1c9e-0a4d-4a7e-8b12-8d5f6c7e9a01 does not exist",
                     *       "timestamp": "2026-09-03T14:35:12.482+02:00"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unexpected failure, or stored match data that is inconsistent (MATCH_STREAM_CORRUPTED, MATCH_PROJECTION_OUT_OF_SYNC). The incident is logged with the timestamp returned in the body. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 500,
                     *       "code": "MATCH_STREAM_CORRUPTED",
                     *       "message": "Stored match data is inconsistent. The incident has been logged.",
                     *       "timestamp": "2026-09-03T14:35:12.482+02:00"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getClub: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClubDTO"];
                };
            };
            /** @description An identifier in the path is not a valid UUID. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 400,
                     *       "code": "ARGUMENT_TYPE_MISMATCH",
                     *       "message": "Failed to convert value of type 'java.lang.String' to required type 'java.util.UUID'",
                     *       "timestamp": "2026-09-03T14:35:12.482+02:00",
                     *       "expectedType": "java.util.UUID",
                     *       "property": "matchId",
                     *       "rejectedValue": "not-a-uuid"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiTypeMismatchError"];
                };
            };
            /** @description No resource exists for the given identifier. The code names the resource: CLUB_NOT_FOUND, PLAYER_NOT_FOUND or MATCH_NOT_FOUND. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 404,
                     *       "code": "MATCH_NOT_FOUND",
                     *       "message": "Match 3f2b1c9e-0a4d-4a7e-8b12-8d5f6c7e9a01 does not exist",
                     *       "timestamp": "2026-09-03T14:35:12.482+02:00"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unexpected failure, or stored match data that is inconsistent (MATCH_STREAM_CORRUPTED, MATCH_PROJECTION_OUT_OF_SYNC). The incident is logged with the timestamp returned in the body. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 500,
                     *       "code": "MATCH_STREAM_CORRUPTED",
                     *       "message": "Stored match data is inconsistent. The incident has been logged.",
                     *       "timestamp": "2026-09-03T14:35:12.482+02:00"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    updateClub: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClubDTO"];
            };
        };
        responses: {
            /** @description Request succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdResponseDTO"];
                };
            };
            /** @description The payload fails validation (code VALIDATION_FAILED), carries a value that cannot be converted to its declared type (ARGUMENT_TYPE_MISMATCH), or references data that does not belong together (CLUB_NOT_IN_MATCH, PLAYER_NOT_IN_CLUB). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiValidationError"] | components["schemas"]["ApiTypeMismatchError"];
                };
            };
            /** @description No access token was sent, or the token is expired or invalid. Written by the security entry point, which emits only a code and a message. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "INSUFFICIENT_AUTHENTICATION",
                     *       "message": "Full authentication is required to access this resource"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The token is valid but the caller lacks the required role. Written by the security access denied handler, which emits only a code and a message. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "ACCESS_DENIED",
                     *       "message": "Access is denied"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No resource exists for the given identifier. The code names the resource: CLUB_NOT_FOUND, PLAYER_NOT_FOUND or MATCH_NOT_FOUND. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 404,
                     *       "code": "MATCH_NOT_FOUND",
                     *       "message": "Match 3f2b1c9e-0a4d-4a7e-8b12-8d5f6c7e9a01 does not exist",
                     *       "timestamp": "2026-09-03T14:35:12.482+02:00"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unexpected failure, or stored match data that is inconsistent (MATCH_STREAM_CORRUPTED, MATCH_PROJECTION_OUT_OF_SYNC). The incident is logged with the timestamp returned in the body. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 500,
                     *       "code": "MATCH_STREAM_CORRUPTED",
                     *       "message": "Stored match data is inconsistent. The incident has been logged.",
                     *       "timestamp": "2026-09-03T14:35:12.482+02:00"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    deleteClub: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resource deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description An identifier in the path is not a valid UUID. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 400,
                     *       "code": "ARGUMENT_TYPE_MISMATCH",
                     *       "message": "Failed to convert value of type 'java.lang.String' to required type 'java.util.UUID'",
                     *       "timestamp": "2026-09-03T14:35:12.482+02:00",
                     *       "expectedType": "java.util.UUID",
                     *       "property": "matchId",
                     *       "rejectedValue": "not-a-uuid"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiTypeMismatchError"];
                };
            };
            /** @description No access token was sent, or the token is expired or invalid. Written by the security entry point, which emits only a code and a message. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "INSUFFICIENT_AUTHENTICATION",
                     *       "message": "Full authentication is required to access this resource"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The token is valid but the caller lacks the required role. Written by the security access denied handler, which emits only a code and a message. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "ACCESS_DENIED",
                     *       "message": "Access is denied"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No resource exists for the given identifier. The code names the resource: CLUB_NOT_FOUND, PLAYER_NOT_FOUND or MATCH_NOT_FOUND. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 404,
                     *       "code": "MATCH_NOT_FOUND",
                     *       "message": "Match 3f2b1c9e-0a4d-4a7e-8b12-8d5f6c7e9a01 does not exist",
                     *       "timestamp": "2026-09-03T14:35:12.482+02:00"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unexpected failure, or stored match data that is inconsistent (MATCH_STREAM_CORRUPTED, MATCH_PROJECTION_OUT_OF_SYNC). The incident is logged with the timestamp returned in the body. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 500,
                     *       "code": "MATCH_STREAM_CORRUPTED",
                     *       "message": "Stored match data is inconsistent. The incident has been logged.",
                     *       "timestamp": "2026-09-03T14:35:12.482+02:00"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getAllMatches: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MatchResponse"][];
                };
            };
            /** @description Unexpected failure, or stored match data that is inconsistent (MATCH_STREAM_CORRUPTED, MATCH_PROJECTION_OUT_OF_SYNC). The incident is logged with the timestamp returned in the body. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 500,
                     *       "code": "MATCH_STREAM_CORRUPTED",
                     *       "message": "Stored match data is inconsistent. The incident has been logged.",
                     *       "timestamp": "2026-09-03T14:35:12.482+02:00"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    registerMatch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMatchRequest"];
            };
        };
        responses: {
            /** @description Resource created. The body carries its identifier. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CreateMatchResponse"];
                };
            };
            /** @description The payload fails validation (code VALIDATION_FAILED), carries a value that cannot be converted to its declared type (ARGUMENT_TYPE_MISMATCH), or references data that does not belong together (CLUB_NOT_IN_MATCH, PLAYER_NOT_IN_CLUB). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiValidationError"] | components["schemas"]["ApiTypeMismatchError"];
                };
            };
            /** @description No access token was sent, or the token is expired or invalid. Written by the security entry point, which emits only a code and a message. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "INSUFFICIENT_AUTHENTICATION",
                     *       "message": "Full authentication is required to access this resource"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The token is valid but the caller lacks the required role. Written by the security access denied handler, which emits only a code and a message. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "ACCESS_DENIED",
                     *       "message": "Access is denied"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No resource exists for the given identifier. The code names the resource: CLUB_NOT_FOUND, PLAYER_NOT_FOUND or MATCH_NOT_FOUND. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 404,
                     *       "code": "MATCH_NOT_FOUND",
                     *       "message": "Match 3f2b1c9e-0a4d-4a7e-8b12-8d5f6c7e9a01 does not exist",
                     *       "timestamp": "2026-09-03T14:35:12.482+02:00"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unexpected failure, or stored match data that is inconsistent (MATCH_STREAM_CORRUPTED, MATCH_PROJECTION_OUT_OF_SYNC). The incident is logged with the timestamp returned in the body. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 500,
                     *       "code": "MATCH_STREAM_CORRUPTED",
                     *       "message": "Stored match data is inconsistent. The incident has been logged.",
                     *       "timestamp": "2026-09-03T14:35:12.482+02:00"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getMatchEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matchId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MatchEventDTO"][];
                };
            };
            /** @description An identifier in the path is not a valid UUID. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 400,
                     *       "code": "ARGUMENT_TYPE_MISMATCH",
                     *       "message": "Failed to convert value of type 'java.lang.String' to required type 'java.util.UUID'",
                     *       "timestamp": "2026-09-03T14:35:12.482+02:00",
                     *       "expectedType": "java.util.UUID",
                     *       "property": "matchId",
                     *       "rejectedValue": "not-a-uuid"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiTypeMismatchError"];
                };
            };
            /** @description No resource exists for the given identifier. The code names the resource: CLUB_NOT_FOUND, PLAYER_NOT_FOUND or MATCH_NOT_FOUND. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 404,
                     *       "code": "MATCH_NOT_FOUND",
                     *       "message": "Match 3f2b1c9e-0a4d-4a7e-8b12-8d5f6c7e9a01 does not exist",
                     *       "timestamp": "2026-09-03T14:35:12.482+02:00"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unexpected failure, or stored match data that is inconsistent (MATCH_STREAM_CORRUPTED, MATCH_PROJECTION_OUT_OF_SYNC). The incident is logged with the timestamp returned in the body. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 500,
                     *       "code": "MATCH_STREAM_CORRUPTED",
                     *       "message": "Stored match data is inconsistent. The incident has been logged.",
                     *       "timestamp": "2026-09-03T14:35:12.482+02:00"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    recordEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matchId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AbandonMatch"] | components["schemas"]["AnnounceAddedTime"] | components["schemas"]["AwardPenalty"] | components["schemas"]["BlowFullTime"] | components["schemas"]["CancelGoal"] | components["schemas"]["EndFirstHalf"] | components["schemas"]["GiveRedCard"] | components["schemas"]["GiveYellowCard"] | components["schemas"]["MissPenalty"] | components["schemas"]["PostponeMatch"] | components["schemas"]["RecordVarDecision"] | components["schemas"]["ScoreGoal"] | components["schemas"]["ScoreOwnGoal"] | components["schemas"]["ScorePenalty"] | components["schemas"]["StartMatch"] | components["schemas"]["StartSecondHalf"] | components["schemas"]["StartVarCheck"] | components["schemas"]["Substitute"];
            };
        };
        responses: {
            /** @description Command accepted and applied to the match. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The payload fails validation (code VALIDATION_FAILED), carries a value that cannot be converted to its declared type (ARGUMENT_TYPE_MISMATCH), or references data that does not belong together (CLUB_NOT_IN_MATCH, PLAYER_NOT_IN_CLUB). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiValidationError"] | components["schemas"]["ApiTypeMismatchError"] | components["schemas"]["ApiError"];
                };
            };
            /** @description No access token was sent, or the token is expired or invalid. Written by the security entry point, which emits only a code and a message. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "INSUFFICIENT_AUTHENTICATION",
                     *       "message": "Full authentication is required to access this resource"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The token is valid but the caller lacks the required role. Written by the security access denied handler, which emits only a code and a message. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "ACCESS_DENIED",
                     *       "message": "Access is denied"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No resource exists for the given identifier. The code names the resource: CLUB_NOT_FOUND, PLAYER_NOT_FOUND or MATCH_NOT_FOUND. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 404,
                     *       "code": "MATCH_NOT_FOUND",
                     *       "message": "Match 3f2b1c9e-0a4d-4a7e-8b12-8d5f6c7e9a01 does not exist",
                     *       "timestamp": "2026-09-03T14:35:12.482+02:00"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The request is valid on its own but breaks a match rule in the current match state. The code names the rule, for example INVALID_MATCH_STATE, PENALTY_ALREADY_PENDING, NO_GOAL_TO_CANCEL, SUBSTITUTION_LIMIT_REACHED or PLAYER_SENT_OFF. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 409,
                     *       "code": "PENALTY_ALREADY_PENDING",
                     *       "message": "A penalty is already pending for this match",
                     *       "timestamp": "2026-09-03T14:35:12.482+02:00"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unexpected failure, or stored match data that is inconsistent (MATCH_STREAM_CORRUPTED, MATCH_PROJECTION_OUT_OF_SYNC). The incident is logged with the timestamp returned in the body. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 500,
                     *       "code": "MATCH_STREAM_CORRUPTED",
                     *       "message": "Stored match data is inconsistent. The incident has been logged.",
                     *       "timestamp": "2026-09-03T14:35:12.482+02:00"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getAllPlayers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerDTO"][];
                };
            };
            /** @description Unexpected failure, or stored match data that is inconsistent (MATCH_STREAM_CORRUPTED, MATCH_PROJECTION_OUT_OF_SYNC). The incident is logged with the timestamp returned in the body. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 500,
                     *       "code": "MATCH_STREAM_CORRUPTED",
                     *       "message": "Stored match data is inconsistent. The incident has been logged.",
                     *       "timestamp": "2026-09-03T14:35:12.482+02:00"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    createPlayer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlayerDTO"];
            };
        };
        responses: {
            /** @description Resource created. The body carries its identifier. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdResponseDTO"];
                };
            };
            /** @description The payload fails validation (code VALIDATION_FAILED), carries a value that cannot be converted to its declared type (ARGUMENT_TYPE_MISMATCH), or references data that does not belong together (CLUB_NOT_IN_MATCH, PLAYER_NOT_IN_CLUB). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiValidationError"] | components["schemas"]["ApiTypeMismatchError"];
                };
            };
            /** @description No access token was sent, or the token is expired or invalid. Written by the security entry point, which emits only a code and a message. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "INSUFFICIENT_AUTHENTICATION",
                     *       "message": "Full authentication is required to access this resource"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The token is valid but the caller lacks the required role. Written by the security access denied handler, which emits only a code and a message. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "ACCESS_DENIED",
                     *       "message": "Access is denied"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No resource exists for the given identifier. The code names the resource: CLUB_NOT_FOUND, PLAYER_NOT_FOUND or MATCH_NOT_FOUND. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 404,
                     *       "code": "MATCH_NOT_FOUND",
                     *       "message": "Match 3f2b1c9e-0a4d-4a7e-8b12-8d5f6c7e9a01 does not exist",
                     *       "timestamp": "2026-09-03T14:35:12.482+02:00"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unexpected failure, or stored match data that is inconsistent (MATCH_STREAM_CORRUPTED, MATCH_PROJECTION_OUT_OF_SYNC). The incident is logged with the timestamp returned in the body. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 500,
                     *       "code": "MATCH_STREAM_CORRUPTED",
                     *       "message": "Stored match data is inconsistent. The incident has been logged.",
                     *       "timestamp": "2026-09-03T14:35:12.482+02:00"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getAllClubs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClubDTO"][];
                };
            };
            /** @description Unexpected failure, or stored match data that is inconsistent (MATCH_STREAM_CORRUPTED, MATCH_PROJECTION_OUT_OF_SYNC). The incident is logged with the timestamp returned in the body. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 500,
                     *       "code": "MATCH_STREAM_CORRUPTED",
                     *       "message": "Stored match data is inconsistent. The incident has been logged.",
                     *       "timestamp": "2026-09-03T14:35:12.482+02:00"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    createClub: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClubDTO"];
            };
        };
        responses: {
            /** @description Resource created. The body carries its identifier. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdResponseDTO"];
                };
            };
            /** @description The payload fails validation (code VALIDATION_FAILED), carries a value that cannot be converted to its declared type (ARGUMENT_TYPE_MISMATCH), or references data that does not belong together (CLUB_NOT_IN_MATCH, PLAYER_NOT_IN_CLUB). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiValidationError"] | components["schemas"]["ApiTypeMismatchError"];
                };
            };
            /** @description No access token was sent, or the token is expired or invalid. Written by the security entry point, which emits only a code and a message. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "INSUFFICIENT_AUTHENTICATION",
                     *       "message": "Full authentication is required to access this resource"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The token is valid but the caller lacks the required role. Written by the security access denied handler, which emits only a code and a message. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "ACCESS_DENIED",
                     *       "message": "Access is denied"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No resource exists for the given identifier. The code names the resource: CLUB_NOT_FOUND, PLAYER_NOT_FOUND or MATCH_NOT_FOUND. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 404,
                     *       "code": "MATCH_NOT_FOUND",
                     *       "message": "Match 3f2b1c9e-0a4d-4a7e-8b12-8d5f6c7e9a01 does not exist",
                     *       "timestamp": "2026-09-03T14:35:12.482+02:00"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unexpected failure, or stored match data that is inconsistent (MATCH_STREAM_CORRUPTED, MATCH_PROJECTION_OUT_OF_SYNC). The incident is logged with the timestamp returned in the body. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 500,
                     *       "code": "MATCH_STREAM_CORRUPTED",
                     *       "message": "Stored match data is inconsistent. The incident has been logged.",
                     *       "timestamp": "2026-09-03T14:35:12.482+02:00"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getMatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matchId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MatchResponse"];
                };
            };
            /** @description An identifier in the path is not a valid UUID. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 400,
                     *       "code": "ARGUMENT_TYPE_MISMATCH",
                     *       "message": "Failed to convert value of type 'java.lang.String' to required type 'java.util.UUID'",
                     *       "timestamp": "2026-09-03T14:35:12.482+02:00",
                     *       "expectedType": "java.util.UUID",
                     *       "property": "matchId",
                     *       "rejectedValue": "not-a-uuid"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiTypeMismatchError"];
                };
            };
            /** @description No resource exists for the given identifier. The code names the resource: CLUB_NOT_FOUND, PLAYER_NOT_FOUND or MATCH_NOT_FOUND. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 404,
                     *       "code": "MATCH_NOT_FOUND",
                     *       "message": "Match 3f2b1c9e-0a4d-4a7e-8b12-8d5f6c7e9a01 does not exist",
                     *       "timestamp": "2026-09-03T14:35:12.482+02:00"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unexpected failure, or stored match data that is inconsistent (MATCH_STREAM_CORRUPTED, MATCH_PROJECTION_OUT_OF_SYNC). The incident is logged with the timestamp returned in the body. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 500,
                     *       "code": "MATCH_STREAM_CORRUPTED",
                     *       "message": "Stored match data is inconsistent. The incident has been logged.",
                     *       "timestamp": "2026-09-03T14:35:12.482+02:00"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getMatchState: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matchId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MatchStateDTO"];
                };
            };
            /** @description An identifier in the path is not a valid UUID. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 400,
                     *       "code": "ARGUMENT_TYPE_MISMATCH",
                     *       "message": "Failed to convert value of type 'java.lang.String' to required type 'java.util.UUID'",
                     *       "timestamp": "2026-09-03T14:35:12.482+02:00",
                     *       "expectedType": "java.util.UUID",
                     *       "property": "matchId",
                     *       "rejectedValue": "not-a-uuid"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiTypeMismatchError"];
                };
            };
            /** @description No resource exists for the given identifier. The code names the resource: CLUB_NOT_FOUND, PLAYER_NOT_FOUND or MATCH_NOT_FOUND. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 404,
                     *       "code": "MATCH_NOT_FOUND",
                     *       "message": "Match 3f2b1c9e-0a4d-4a7e-8b12-8d5f6c7e9a01 does not exist",
                     *       "timestamp": "2026-09-03T14:35:12.482+02:00"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unexpected failure, or stored match data that is inconsistent (MATCH_STREAM_CORRUPTED, MATCH_PROJECTION_OUT_OF_SYNC). The incident is logged with the timestamp returned in the body. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 500,
                     *       "code": "MATCH_STREAM_CORRUPTED",
                     *       "message": "Stored match data is inconsistent. The incident has been logged.",
                     *       "timestamp": "2026-09-03T14:35:12.482+02:00"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    index: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
}
